#!/usr/bin/env bash
set -euo pipefail

MATUGEN_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/matugen"
NVIM_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"

PALETTE_TEMPLATE="$MATUGEN_DIR/templates/nvim-matugen-palette.lua"
MATUGEN_CONFIG="$MATUGEN_DIR/config.toml"

NVIM_COLORS_DIR="$NVIM_DIR/colors"
NVIM_LUA_DIR="$NVIM_DIR/lua"
NVIM_MATUGEN_DIR="$NVIM_LUA_DIR/matugen"
NVIM_PLUGINS_DIR="$NVIM_LUA_DIR/plugins"
NVIM_CONFIG_DIR="$NVIM_LUA_DIR/config"

GENERATED_PALETTE="$NVIM_MATUGEN_DIR/palette.lua"
COLORSCHEME_FILE="$NVIM_COLORS_DIR/matugen.lua"
LAZYVIM_PLUGIN_FILE="$NVIM_PLUGINS_DIR/matugen-colorscheme.lua"
AUTOCMDS_FILE="$NVIM_CONFIG_DIR/autocmds.lua"

START_MARKER="# >>> lazyvim-matugen.nvim"
END_MARKER="# <<< lazyvim-matugen.nvim"

LUA_START_MARKER="-- >>> lazyvim-matugen.nvim"
LUA_END_MARKER="-- <<< lazyvim-matugen.nvim"

mkdir -p \
	"$MATUGEN_DIR/templates" \
	"$NVIM_COLORS_DIR" \
	"$NVIM_MATUGEN_DIR" \
	"$NVIM_PLUGINS_DIR" \
	"$NVIM_CONFIG_DIR"

write_file() {
	local path="$1"
	local content="$2"

	if [[ -f "$path" ]] && cmp -s "$path" <(printf '%s\n' "$content"); then
		echo "unchanged: $path"
		return
	fi

	printf '%s\n' "$content" >"$path"
	echo "wrote: $path"
}

patch_block() {
	local path="$1"
	local start="$2"
	local end="$3"
	local block="$4"

	touch "$path"

	if grep -qF "$start" "$path"; then
		awk -v start="$start" -v end="$end" -v block="$block" '
      BEGIN { in_block = 0 }
      index($0, start) {
        print block
        in_block = 1
        next
      }
      index($0, end) {
        in_block = 0
        next
      }
      !in_block { print }
    ' "$path" >"$path.tmp"
		mv "$path.tmp" "$path"
	else
		{
			cat "$path"
			printf '\n%s\n' "$block"
		} >"$path.tmp"
		mv "$path.tmp" "$path"
	fi

	echo "patched: $path"
}

PALETTE_TEMPLATE_CONTENT='-- Generated by matugen. Do not edit directly.
return {
  background = "{{ colors.background.default.hex }}",
  on_background = "{{ colors.on_background.default.hex }}",

  surface = "{{ colors.surface.default.hex }}",
  on_surface = "{{ colors.on_surface.default.hex }}",
  surface_variant = "{{ colors.surface_variant.default.hex }}",
  on_surface_variant = "{{ colors.on_surface_variant.default.hex }}",

  surface_container_low = "{{ colors.surface_container_low.default.hex }}",
  surface_container = "{{ colors.surface_container.default.hex }}",
  surface_container_high = "{{ colors.surface_container_high.default.hex }}",

  primary = "{{ colors.primary.default.hex }}",
  on_primary = "{{ colors.on_primary.default.hex }}",
  primary_container = "{{ colors.primary_container.default.hex }}",
  on_primary_container = "{{ colors.on_primary_container.default.hex }}",

  secondary = "{{ colors.secondary.default.hex }}",
  on_secondary = "{{ colors.on_secondary.default.hex }}",
  secondary_container = "{{ colors.secondary_container.default.hex }}",
  on_secondary_container = "{{ colors.on_secondary_container.default.hex }}",

  tertiary = "{{ colors.tertiary.default.hex }}",
  on_tertiary = "{{ colors.on_tertiary.default.hex }}",
  tertiary_container = "{{ colors.tertiary_container.default.hex }}",
  on_tertiary_container = "{{ colors.on_tertiary_container.default.hex }}",

  error = "{{ colors.error.default.hex }}",
  on_error = "{{ colors.on_error.default.hex }}",
  error_container = "{{ colors.error_container.default.hex }}",
  on_error_container = "{{ colors.on_error_container.default.hex }}",

  outline = "{{ colors.outline.default.hex }}",
  outline_variant = "{{ colors.outline_variant.default.hex }}",
}'

COLORSCHEME_CONTENT='-- Static colorscheme loader.
-- Palette is generated by matugen at lua/matugen/palette.lua.

vim.cmd("highlight clear")

if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "matugen"
vim.o.termguicolors = true
vim.o.background = "dark"

local ok, c = pcall(require, "matugen.palette")
if not ok then
  c = {
    background = "#111318",
    on_background = "#e2e2e9",
    surface = "#111318",
    on_surface = "#e2e2e9",
    surface_variant = "#44474f",
    on_surface_variant = "#c4c6d0",
    surface_container_low = "#191c20",
    surface_container = "#1d2024",
    surface_container_high = "#282a2f",
    primary = "#aac7ff",
    on_primary = "#0a305f",
    primary_container = "#284777",
    on_primary_container = "#d6e3ff",
    secondary = "#bec6dc",
    on_secondary = "#283141",
    secondary_container = "#3e4759",
    on_secondary_container = "#dae2f9",
    tertiary = "#ddbce0",
    on_tertiary = "#3f2844",
    tertiary_container = "#573e5c",
    on_tertiary_container = "#fad8fd",
    error = "#ffb4ab",
    on_error = "#690005",
    error_container = "#93000a",
    on_error_container = "#ffdad6",
    outline = "#8e9099",
    outline_variant = "#44474f",
  }
end

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Core UI
hi("Normal", { fg = c.on_surface, bg = c.background })
hi("NormalNC", { fg = c.on_surface, bg = c.background })
hi("NormalFloat", { fg = c.on_surface, bg = c.surface_container })
hi("FloatBorder", { fg = c.outline, bg = c.surface_container })
hi("WinSeparator", { fg = c.outline_variant })
hi("CursorLine", { bg = c.surface_container_low })
hi("CursorLineNr", { fg = c.primary, bold = true })
hi("LineNr", { fg = c.outline })
hi("SignColumn", { bg = c.background })
hi("ColorColumn", { bg = c.surface_container })
hi("VertSplit", { fg = c.outline_variant })
hi("Visual", { bg = c.primary_container, fg = c.on_primary_container })
hi("StatusLine", { fg = c.on_surface, bg = c.surface_container_high })
hi("StatusLineNC", { fg = c.outline, bg = c.surface_container })

-- Menus
hi("Pmenu", { fg = c.on_surface, bg = c.surface_container })
hi("PmenuSel", { fg = c.on_primary_container, bg = c.primary_container })
hi("PmenuSbar", { bg = c.surface_container_high })
hi("PmenuThumb", { bg = c.primary })
hi("WildMenu", { fg = c.on_primary_container, bg = c.primary_container })

-- Search
hi("Search", { fg = c.on_tertiary_container, bg = c.tertiary_container })
hi("IncSearch", { fg = c.on_primary, bg = c.primary })
hi("CurSearch", { fg = c.on_primary, bg = c.primary })

-- Syntax
hi("Comment", { fg = c.outline, italic = true })
hi("Constant", { fg = c.tertiary })
hi("String", { fg = c.secondary })
hi("Character", { fg = c.secondary })
hi("Number", { fg = c.tertiary })
hi("Boolean", { fg = c.tertiary })
hi("Float", { fg = c.tertiary })

hi("Identifier", { fg = c.on_surface })
hi("Function", { fg = c.primary })

hi("Statement", { fg = c.primary })
hi("Conditional", { fg = c.primary })
hi("Repeat", { fg = c.primary })
hi("Label", { fg = c.primary })
hi("Operator", { fg = c.on_surface_variant })
hi("Keyword", { fg = c.primary })
hi("Exception", { fg = c.error })

hi("PreProc", { fg = c.tertiary })
hi("Include", { fg = c.primary })
hi("Define", { fg = c.primary })
hi("Macro", { fg = c.tertiary })

hi("Type", { fg = c.secondary })
hi("StorageClass", { fg = c.secondary })
hi("Structure", { fg = c.secondary })
hi("Typedef", { fg = c.secondary })

hi("Special", { fg = c.tertiary })
hi("Underlined", { fg = c.primary, underline = true })
hi("Error", { fg = c.on_error, bg = c.error })
hi("Todo", { fg = c.on_tertiary_container, bg = c.tertiary_container, bold = true })

-- Diagnostics
hi("DiagnosticError", { fg = c.error })
hi("DiagnosticWarn", { fg = c.tertiary })
hi("DiagnosticInfo", { fg = c.primary })
hi("DiagnosticHint", { fg = c.secondary })
hi("DiagnosticOk", { fg = c.primary })

hi("DiagnosticUnderlineError", { sp = c.error, undercurl = true })
hi("DiagnosticUnderlineWarn", { sp = c.tertiary, undercurl = true })
hi("DiagnosticUnderlineInfo", { sp = c.primary, undercurl = true })
hi("DiagnosticUnderlineHint", { sp = c.secondary, undercurl = true })

-- Git / diff
hi("DiffAdd", { fg = c.secondary, bg = c.secondary_container })
hi("DiffChange", { fg = c.tertiary, bg = c.tertiary_container })
hi("DiffDelete", { fg = c.error, bg = c.error_container })
hi("DiffText", { fg = c.on_primary_container, bg = c.primary_container })

hi("GitSignsAdd", { fg = c.secondary })
hi("GitSignsChange", { fg = c.tertiary })
hi("GitSignsDelete", { fg = c.error })

-- Treesitter common captures
hi("@comment", { fg = c.outline, italic = true })
hi("@string", { fg = c.secondary })
hi("@number", { fg = c.tertiary })
hi("@boolean", { fg = c.tertiary })
hi("@keyword", { fg = c.primary })
hi("@keyword.function", { fg = c.primary })
hi("@function", { fg = c.primary })
hi("@function.call", { fg = c.primary })
hi("@constructor", { fg = c.secondary })
hi("@type", { fg = c.secondary })
hi("@variable", { fg = c.on_surface })
hi("@property", { fg = c.on_surface_variant })
hi("@punctuation", { fg = c.on_surface_variant })
hi("@operator", { fg = c.on_surface_variant })

-- LazyVim-ish plugins
hi("TelescopeNormal", { fg = c.on_surface, bg = c.surface_container })
hi("TelescopeBorder", { fg = c.outline, bg = c.surface_container })
hi("TelescopeSelection", { fg = c.on_primary_container, bg = c.primary_container })
hi("TelescopeMatching", { fg = c.primary, bold = true })

hi("NeoTreeNormal", { fg = c.on_surface, bg = c.background })
hi("NeoTreeNormalNC", { fg = c.on_surface, bg = c.background })
hi("NeoTreeDirectoryName", { fg = c.primary })
hi("NeoTreeFileNameOpened", { fg = c.primary, bold = true })

hi("WhichKey", { fg = c.primary })
hi("WhichKeyDesc", { fg = c.on_surface })
hi("WhichKeyGroup", { fg = c.secondary })
hi("WhichKeyBorder", { fg = c.outline })

hi("LazyNormal", { fg = c.on_surface, bg = c.surface_container })
hi("MasonNormal", { fg = c.on_surface, bg = c.surface_container })
'

LAZYVIM_PLUGIN_CONTENT='return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "matugen",
    },
  },
}
'

AUTOCMD_BLOCK="$LUA_START_MARKER
-- Reload matugen colorscheme when matugen sends SIGUSR1.
-- Keep signal handle global so Lua GC does not collect it.
do
  local uv = vim.uv or vim.loop
  if uv and uv.new_signal then
    _G.matugen_reload_signal = _G.matugen_reload_signal or uv.new_signal()

    pcall(function()
      _G.matugen_reload_signal:start(\"sigusr1\", vim.schedule_wrap(function()
        pcall(vim.cmd.colorscheme, \"matugen\")
        vim.notify(\"Reloaded matugen colorscheme\", vim.log.levels.INFO)
      end))
    end)
  end
end
$LUA_END_MARKER"

MATUGEN_BLOCK="$START_MARKER
[templates.nvim_lazyvim]
input_path = '$PALETTE_TEMPLATE'
output_path = '$GENERATED_PALETTE'
post_hook = 'pkill -SIGUSR1 nvim || true'
$END_MARKER"

write_file "$PALETTE_TEMPLATE" "$PALETTE_TEMPLATE_CONTENT"
write_file "$COLORSCHEME_FILE" "$COLORSCHEME_CONTENT"
write_file "$LAZYVIM_PLUGIN_FILE" "$LAZYVIM_PLUGIN_CONTENT"

patch_block "$AUTOCMDS_FILE" "$LUA_START_MARKER" "$LUA_END_MARKER" "$AUTOCMD_BLOCK"
patch_block "$MATUGEN_CONFIG" "$START_MARKER" "$END_MARKER" "$MATUGEN_BLOCK"

if [[ $# -gt 0 ]]; then
	WALLPAPER="$1"

	if ! command -v matugen >/dev/null 2>&1; then
		echo "matugen not found in PATH. Config written, but palette not generated."
		exit 0
	fi

	if [[ ! -f "$WALLPAPER" ]]; then
		echo "wallpaper not found: $WALLPAPER"
		exit 1
	fi

	matugen image "$WALLPAPER"
fi

cat <<EOF

Done.

Created:
  $PALETTE_TEMPLATE
  $COLORSCHEME_FILE
  $LAZYVIM_PLUGIN_FILE
  $GENERATED_PALETTE will be generated by matugen

Patched:
  $MATUGEN_CONFIG
  $AUTOCMDS_FILE

Test:
  matugen image /path/to/wallpaper.jpg
  nvim
  :colorscheme matugen

EOF
